//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMaker.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_cn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_cn() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataMaker.Languages.zh_cn", typeof(zh_cn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string description_ {
            get {
                return ResourceManager.GetString("description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一段描述，此字段可以为空。在数据包列表下，光标移动到对应的数据包时会显示描述。 的本地化字符串。
        /// </summary>
        internal static string description_pack_description {
            get {
                return ResourceManager.GetString("description_pack_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据包版本，可以是任何数字。 的本地化字符串。
        /// </summary>
        internal static string description_pack_packformat {
            get {
                return ResourceManager.GetString("description_pack_packformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存放数据包信息。展开进行编辑。 的本地化字符串。
        /// </summary>
        internal static string description_packmcmeta_pack {
            get {
                return ResourceManager.GetString("description_packmcmeta_pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该标签是否要覆盖掉低优先级的数据包中的相同标签。设置为“否”将会把内容合并到该标签，而不是覆盖。 的本地化字符串。
        /// </summary>
        internal static string description_tag_replace {
            get {
                return ResourceManager.GetString("description_tag_replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一堆物品，方块或函数。可以放入其他同类型的标签。 的本地化字符串。
        /// </summary>
        internal static string description_tag_values {
            get {
                return ResourceManager.GetString("description_tag_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string displayname_ {
            get {
                return ResourceManager.GetString("displayname_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string displayname_pack_description {
            get {
                return ResourceManager.GetString("displayname_pack_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        internal static string displayname_pack_packformat {
            get {
                return ResourceManager.GetString("displayname_pack_packformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        internal static string displayname_packmcmeta_pack {
            get {
                return ResourceManager.GetString("displayname_packmcmeta_pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 覆盖 的本地化字符串。
        /// </summary>
        internal static string displayname_tag_replace {
            get {
                return ResourceManager.GetString("displayname_tag_replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        internal static string displayname_tag_values {
            get {
                return ResourceManager.GetString("displayname_tag_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加... 的本地化字符串。
        /// </summary>
        internal static string filetree_add {
            get {
                return ResourceManager.GetString("filetree_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收起 的本地化字符串。
        /// </summary>
        internal static string filetree_collapse {
            get {
                return ResourceManager.GetString("filetree_collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string filetree_copy {
            get {
                return ResourceManager.GetString("filetree_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪切 的本地化字符串。
        /// </summary>
        internal static string filetree_cut {
            get {
                return ResourceManager.GetString("filetree_cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string filetree_delete {
            get {
                return ResourceManager.GetString("filetree_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string filetree_edit {
            get {
                return ResourceManager.GetString("filetree_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 展开 的本地化字符串。
        /// </summary>
        internal static string filetree_expand {
            get {
                return ResourceManager.GetString("filetree_expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        internal static string filetree_file {
            get {
                return ResourceManager.GetString("filetree_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹 的本地化字符串。
        /// </summary>
        internal static string filetree_folder {
            get {
                return ResourceManager.GetString("filetree_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在：{0} 的本地化字符串。
        /// </summary>
        internal static string filetree_msgbox_exist {
            get {
                return ResourceManager.GetString("filetree_msgbox_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 不是空的文件夹，也不像一个数据包，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string filetree_msgbox_notadatapack {
            get {
                return ResourceManager.GetString("filetree_msgbox_notadatapack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要删除 {0} ？ 的本地化字符串。
        /// </summary>
        internal static string filetree_msgbox_suretodelete {
            get {
                return ResourceManager.GetString("filetree_msgbox_suretodelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴 的本地化字符串。
        /// </summary>
        internal static string filetree_paste {
            get {
                return ResourceManager.GetString("filetree_paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string filetree_properties_name {
            get {
                return ResourceManager.GetString("filetree_properties_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径 的本地化字符串。
        /// </summary>
        internal static string filetree_properties_path {
            get {
                return ResourceManager.GetString("filetree_properties_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        internal static string filetree_properties_type {
            get {
                return ResourceManager.GetString("filetree_properties_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        internal static string filetree_property {
            get {
                return ResourceManager.GetString("filetree_property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名 的本地化字符串。
        /// </summary>
        internal static string filetree_rename {
            get {
                return ResourceManager.GetString("filetree_rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度 的本地化字符串。
        /// </summary>
        internal static string global_advancement {
            get {
                return ResourceManager.GetString("global_advancement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方块 的本地化字符串。
        /// </summary>
        internal static string global_block {
            get {
                return ResourceManager.GetString("global_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据 的本地化字符串。
        /// </summary>
        internal static string global_data {
            get {
                return ResourceManager.GetString("global_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据包 的本地化字符串。
        /// </summary>
        internal static string global_datapack {
            get {
                return ResourceManager.GetString("global_datapack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 函数 的本地化字符串。
        /// </summary>
        internal static string global_function {
            get {
                return ResourceManager.GetString("global_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品 的本地化字符串。
        /// </summary>
        internal static string global_item {
            get {
                return ResourceManager.GetString("global_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战利品表 的本地化字符串。
        /// </summary>
        internal static string global_loottable {
            get {
                return ResourceManager.GetString("global_loottable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命名空间 的本地化字符串。
        /// </summary>
        internal static string global_namespace {
            get {
                return ResourceManager.GetString("global_namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配方 的本地化字符串。
        /// </summary>
        internal static string global_recipe {
            get {
                return ResourceManager.GetString("global_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string global_settings {
            get {
                return ResourceManager.GetString("global_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结构 的本地化字符串。
        /// </summary>
        internal static string global_structure {
            get {
                return ResourceManager.GetString("global_structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        internal static string global_tag {
            get {
                return ResourceManager.GetString("global_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zip文件已成功导出到 {0} 的本地化字符串。
        /// </summary>
        internal static string mainform_msgbox_exportzipsuccessfully {
            get {
                return ResourceManager.GetString("mainform_msgbox_exportzipsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 {0} 不合法，文件名只能包含小写字母、数字、下划线“_” 和 横线“-”。不建议使用拼音 的本地化字符串。
        /// </summary>
        internal static string mainform_msgbox_notalegalname {
            get {
                return ResourceManager.GetString("mainform_msgbox_notalegalname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否将你所作的更改保存到 {0} ？ 的本地化字符串。
        /// </summary>
        internal static string mainform_msgbox_savechangedornot {
            get {
                return ResourceManager.GetString("mainform_msgbox_savechangedornot", resourceCulture);
            }
        }
    }
}
